{% set name = "interleafq" %}
{% set version = "1.0" %}
{% set sha256 = "??" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/quadram-institute-bioscience/interleafq/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: generic
 

requirements:
  host:
    - perl
    - perl-getopt-long
    - perl-fastx-reader
  run:
    - perl
    - perl-getopt-long
    - perl-fastx-reader

test:
  commands:
    - interleafq.pl --version

about:
  home: https://github.com/quadram-institute-bioscience/interleafq/
  license: MIT
  summary: A tool to interleave and deinterleave FASTQ files with controls and support for gzipped input

